[package]
name = "bevy-shader-testing"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.16" }

[features]
dev = [
    "bevy/dynamic_linking",
    "bevy/file_watcher",
]

[build-dependencies]
embed-resource = "1"
