# Install clang and mold with the package manager, use nightly
# This is from: https://gist.github.com/janhohenheim/5731c11e91736bab5e9ef58c2a982c36

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-Clink-arg=-fuse-ld=mold",
    # Needed for flamegraph: https://github.com/flamegraph-rs/flamegraph?tab=readme-ov-file#linux
    # "-Clink-arg=-Wl,--no-rosegment",
    # Needed for flamegraph: https://github.com/bevyengine/bevy/blob/main/docs/profiling.md#perf-flame-graph
    # "-Cforce-frame-pointers=y",

    # Nightly
    "-Zshare-generics=y",
    "-Zthreads=8",
]
rustdocflags = [
    "-Clink-arg=-fuse-ld=mold",
    # Nightly
    "-Zshare-generics=y",
    "-Zthreads=8",
]

